name: 'Setup Dependencies'
description: 'Setup Node.js and install dependencies with caching'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20'
  package-manager:
    description: 'Package manager to use (npm, yarn, bun)'
    required: false
    default: 'npm'
  working-directory:
    description: 'Working directory'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: 🔧 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.package-manager }}

    - name: 📦 Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ "${{ inputs.package-manager }}" = "npm" ]; then
          if [ -f "package-lock.json" ]; then
            npm ci
          else
            npm install
          fi
        elif [ "${{ inputs.package-manager }}" = "yarn" ]; then
          if [ -f "yarn.lock" ]; then
            yarn install --frozen-lockfile
          else
            yarn install
          fi
        elif [ "${{ inputs.package-manager }}" = "bun" ]; then
          if [ -f "bun.lockb" ]; then
            bun install --frozen-lockfile
          else
            bun install
          fi
        else
          echo "Unsupported package manager: ${{ inputs.package-manager }}"
          exit 1
        fi