version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      development-dependencies:
        dependency-type: development
        patterns:
          - '*'
      production-dependencies:
        dependency-type: production
        patterns:
          - '*'
    versioning-strategy: increase
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - security
    reviewers:
      - CodySwannGT
    assignees:
      - CodySwannGT
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - '*'
    labels:
      - dependencies
      - github-actions
    reviewers:
      - CodySwannGT
    assignees:
      - CodySwannGT
    commit-message:
      prefix: ci
      include: scope
