/**
 * Setup file for CI environment
 * Creates necessary directories for tests to pass in CI
 */
import fs from 'fs-extra';
import path from 'path';

// Create tmp directory for tests
const tmpDir = path.join(process.cwd(), 'tmp');
console.log(`Setting up CI test environment: ${tmpDir}`);

// Create temp directory
fs.ensureDirSync(tmpDir);

// Create .roo directory
const rooDir = path.join(tmpDir, '.roo');
fs.ensureDirSync(rooDir);
fs.ensureDirSync(path.join(rooDir, 'rules'));

// Create mock files to help tests pass
fs.writeFileSync(path.join(tmpDir, '.rooignore'), '# Autogenerated file for tests\nnode_modules\ndist\nbuild');
fs.writeFileSync(path.join(tmpDir, 'CLAUDE.md'), '# Mock CLAUDE.md file for tests');
fs.writeFileSync(path.join(tmpDir, '.mcp.json'), '{"mcpServers":{}}');

console.log('CI test environment ready');