version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the root directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Group all updates together
    groups:
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
      production-dependencies:
        dependency-type: "production"
        patterns:
          - "*"
    # Set version strategy
    versioning-strategy: increase
    # Include dependency scope updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Limit the number of open PRs
    open-pull-requests-limit: 10
    # Apply security labels to security updates
    labels:
      - "dependencies"
      - "security"
    # Specify reviewers for pull requests
    reviewers:
      - "CodySwannGT"
    # Assign PRs to specific user
    assignees:
      - "CodySwannGT"
    # Set commit message style
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Group all updates together
    groups:
      github-actions:
        patterns:
          - "*"
    # Apply appropriate labels
    labels:
      - "dependencies"
      - "github-actions"
    # Specify reviewers
    reviewers:
      - "CodySwannGT"
    # Assign PRs
    assignees:
      - "CodySwannGT"
    # Set commit message style
    commit-message:
      prefix: "ci"
      include: "scope"