name: Create Issue on Workflow Failure

on:
  workflow_call:
    inputs:
      workflow_name:
        required: true
        type: string
        description: "Name of the workflow that failed"
      failed_job:
        required: false
        type: string
        description: "Name of the job that failed (optional)"
    secrets:
      PAT:
        required: true

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const { owner, repo } = context.repo;
            const runId = context.runId;
            const runUrl = `https://github.com/${owner}/${repo}/actions/runs/${runId}`;

            const workflowName = '${{ inputs.workflow_name }}';
            const failedJob = '${{ inputs.failed_job }}' || 'Unknown';

            const title = `🚨 Workflow Failure: ${workflowName}${failedJob !== 'Unknown' ? ` - ${failedJob}` : ''}`;
            const body = `
            ## Workflow Failure

            The "${workflowName}" workflow has failed${failedJob !== 'Unknown' ? ` in job: **${failedJob}**` : ''}.

            ### Details
            - **Workflow Run**: [View Run Details](${runUrl})
            - **Commit**: ${context.sha}
            - **Commit Message**: ${context.payload.head_commit ? context.payload.head_commit.message : 'N/A'}
            - **Triggered by**: ${context.actor}
            - **Failed at**: ${new Date().toISOString()}

            Please investigate the workflow logs for more details on the failure.
            `;

            await github.rest.issues.create({
              owner,
              repo,
              title,
              body,
              labels: ['bug', 'automation', 'ci-failure']
            });

            console.log(`Issue created for workflow failure: ${runUrl}`);
