name: Documentation

on:
  push:
    branches: [main]
    paths:
      - "**/*.md"
      - ".github/workflows/docs.yml"
  pull_request:
    paths:
      - "**/*.md"
      - ".github/workflows/docs.yml"

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Lint Markdown files
        run: npm run lint-md
